### ISSUE TITLE
bug: currency update not working

### ISSUE THREAD

**Issue by christiantrummer** [jurajkusnier/bitcoin-balance-check#1]
when i click on settings to choose the currency i always see a red error message "Network Connection Error" - no matter which currency i choose. therefore each bitcoin wallet has a value of 0.

the coinmarketcap API which is used here is not available anymore: https://github.com/jurajkusnier/bitcoin-balance-check/blob/master/app/src/main/java/com/jurajkusnier/bitcoinwalletbalance/data/api/CoinmarketcapApiService.kt#L14

https://api.coinmarketcap.com/v2/ticker/1/?convert=EUR
WARNING: This API is now offline. Please switch to the new CoinMarketCap API. (https://pro.coinmarketcap.com/migrate/)

**Comment by jurajkusnier** [comment]
Thank you for reporting this bug. It's fixed now.
